INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Afghanistan', 'AF', 'AFG', '4');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Albania', 'AL', 'ALB', '8');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Algeria', 'DZ', 'DZA', '12');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('American Samoa', 'AS', 'ASM', '16');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Andorra', 'AD', 'AND', '20');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Angola', 'AO', 'AGO', '24');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Anguilla', 'AI', 'AIA', '660');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Antarctica', 'AQ', 'ATA', '10');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Antigua and Barbuda', 'AG', 'ATG', '28');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Argentina', 'AR', 'ARG', '32');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Armenia', 'AM', 'ARM', '51');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Aruba', 'AW', 'ABW', '533');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Australia', 'AU', 'AUS', '36');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Austria', 'AT', 'AUT', '40');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Azerbaijan', 'AZ', 'AZE', '31');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bahamas', 'BS', 'BHS', '44');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bahrain', 'BH', 'BHR', '48');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bangladesh', 'BD', 'BGD', '50');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Barbados', 'BB', 'BRB', '52');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Belarus', 'BY', 'BLR', '112');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Belgium', 'BE', 'BEL', '56');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Belize', 'BZ', 'BLZ', '84');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Benin', 'BJ', 'BEN', '204');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bermuda', 'BM', 'BMU', '60');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bhutan', 'BT', 'BTN', '64');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bolivia', 'BO', 'BOL', '68');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bonaire, Sint Eustatius, and Saba', 'BQ', 'BES', '535');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bosnia and Herzegovina', 'BA', 'BIH', '70');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Botswana', 'BW', 'BWA', '72');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bouvet Island', 'BV', 'BVT', '74');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Brazil', 'BR', 'BRA', '76');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('British Indian Ocean Territory', 'IO', 'IOT', '86');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('British Virgin Islands', 'VG', 'VGB', '92');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Brunei Darussalam', 'BN', 'BRN', '96');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Bulgaria', 'BG', 'BGR', '100');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Burkina Faso', 'BF', 'BFA', '854');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Burundi', 'BI', 'BDI', '108');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Cambodia', 'KH', 'KHM', '116');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Cameroon, United Republic of', 'CM', 'CMR', '120');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Canada', 'CA', 'CAN', '124');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Cape Verde Island', 'CV', 'CPV', '132');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Cayman Islands', 'KY', 'CYM', '136');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Central African Republic', 'CF', 'CAF', '140');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Chad', 'TD', 'TCD', '148');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Chile', 'CL', 'CHL', '152');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('China', 'CN', 'CHN', '156');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Christmas Island', 'CX', 'CXR', '162');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Cocos (Keeling) Islands', 'CC', 'CCK', '166');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Colombia', 'CO', 'COL', '170');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Comoros', 'KM', 'COM', '174');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Congo', 'CG', 'COG', '178');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Cook Islands', 'CK', 'COK', '184');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Costa Rica', 'CR', 'CRI', '188');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Côte d\'Ivoire (Ivory Coast)', 'CI', 'CIV', '384');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Croatia', 'HR', 'HRV', '191');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Cuba', 'CU', 'CUB', '192');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Curacao', 'CW', 'CUW', '531');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Cyprus', 'CY', 'CYP', '196');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Czech Republic', 'CZ', 'CZE', '203');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Democratic Republic of the Congo', 'CD', 'COD', '180');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Denmark', 'DK', 'DNK', '208');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Djibouti', 'DJ', 'DJI', '262');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Dominica', 'DM', 'DMA', '212');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Dominican Republic', 'DO', 'DOM', '214');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Ecuador', 'EC', 'ECU', '218');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Egypt', 'EG', 'EGY', '818');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('El Salvador', 'SV', 'SLV', '222');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Equatorial Guinea', 'GQ', 'GNQ', '226');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Eritrea', 'ER', 'ERI', '232');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Estonia', 'EE', 'EST', '233');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Ethiopia', 'ET', 'ETH', '231');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Falkland Islands (Malvinas)', 'FK', 'FLK', '238');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Faroe Islands', 'FO', 'FRO', '208');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Fiji', 'FJ', 'FJI', '242');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Finland', 'FI', 'FIN', '246');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('France', 'FR', 'FRA', '250');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('France,Metropolitan', 'FX', 'FXX', '249');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('French Guiana', 'GF', 'GUF', '254');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('French Polynesia', 'PF', 'PYF', '258');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('French Southern Territories', 'TF', 'ATF', '260');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Gabon', 'GA', 'GAB', '266');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Gambia', 'GM', 'GMB', '270');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Georgia', 'GE', 'GEO', '268');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Germany', 'DE', 'DEU', '276');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Ghana', 'GH', 'GHA', '288');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Gibralter', 'GI', 'GIB', '292');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Greece', 'GR', 'GRC', '300');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Greenland', 'GL', 'GRL', '304');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Grenada', 'GD', 'GRD', '308');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Guadeloupe', 'GP', 'GLP', '312');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Guam', 'GU', 'GUM', '316');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Guatemala', 'GT', 'GTM', '320');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Guinea', 'GN', 'GIN', '324');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Guinea-Bissau', 'GW', 'GNB', '624');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Guyana', 'GY', 'GUY', '328');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Haiti', 'HT', 'HTI', '332');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Heard and McDonald Islands', 'HM', 'HMD', '334');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Holy See (Vatican City State)', 'VA', 'VAT', '336');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Honduras', 'HN', 'HND', '340');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Hong Kong', 'HK', 'HKG', '344');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Hungary', 'HU', 'HUN', '348');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Iceland', 'IS', 'ISL', '352');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('India', 'IN', 'IND', '356');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Indonesia', 'ID', 'IDN', '360');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Iran, Islamic Republic of', 'IR', 'IRN', '364');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Iraq', 'IQ', 'IRQ', '368');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Ireland, Republic of', 'IE', 'IRL', '372');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Isle of Man', 'IM', 'IMN', '833');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Israel', 'IL', 'ISR', '376');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Italy', 'IT', 'ITA', '380');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Jamaica', 'JM', 'JAM', '388');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Japan', 'JP', 'JPN', '392');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Jordan', 'JO', 'JOR', '400');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Kazakhstan', 'KZ', 'KAZ', '398');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Kenya', 'KE', 'KEN', '404');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Kiribati', 'KI', 'KIR', '296');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Korea, Democratic Peoples Republic of', 'KP', 'PRK', '408');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Korea, Republic of', 'KR', 'KOR', '410');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Kuwait', 'KW', 'KWT', '414');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Kyrgyzstan', 'KG', 'KGZ', '417');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Laos', 'LA', 'LAO', '418');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Latvia', 'LV', 'LVA', '428');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Lebanon', 'LB', 'LBN', '422');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Lesotho', 'LS', 'LSO', '426');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Liberia', 'LR', 'LBR', '430');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Libyan Arab Jamahiriya', 'LY', 'LBY', '434');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Liechtenstein', 'LI', 'LIE', '438');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Lithuania', 'LT', 'LTU', '440');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Luxembourg', 'LU', 'LUX', '442');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Macau, China', 'MO', 'MAC', '446');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Macedonia', 'MK', 'MKD', '807');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Madagascar', 'MG', 'MDG', '450');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Malawi', 'MW', 'MWI', '454');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Malaysia', 'MY', 'MYS', '458');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Maldives', 'MV', 'MDV', '462');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Mali', 'ML', 'MLI', '466');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Malta', 'MT', 'MLT', '470');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Marshall Islands', 'MH', 'MHL', '584');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Martinique', 'MQ', 'MTQ', '474');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Mauritania', 'MR', 'MRT', '478');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Mauritius', 'MU', 'MUS', '480');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Mayotte', 'YT', 'MYT', '175');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Mexico', 'MX', 'MEX', '484');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Micronesia', 'FM', 'FSM', '583');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Moldova, Republic of', 'MD', 'MDA', '498');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Monaco', 'MC', 'MCO', '492');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Mongolia', 'MN', 'MNG', '496');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Montenegro', 'ME', 'MNE', '499');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Morocco', 'MA', 'MAR', '504');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Mozambique', 'MZ', 'MOZ', '508');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('MS', 'MSR', '500', '1');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Myanmar', 'MM', 'MMR', '104');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Namibia', 'NA', 'NAM', '516');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Nauru', 'NR', 'NRU', '520');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Nepal', 'NP', 'NPL', '524');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Netherlands', 'NL', 'NLD', '528');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('New Caledonia', 'NC', 'NCL', '540');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('New Zealand', 'NZ', 'NZL', '554');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Nicaragua', 'NI', 'NIC', '558');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Niger', 'NE', 'NER', '562');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Nigeria', 'NG', 'NGA', '566');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Niue', 'NU', 'NIU', '570');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Norfolk Island', 'NF', 'NFK', '574');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Northern Mariana Islands', 'MP', 'MNP', '580');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Norway', 'NO', 'NOR', '578');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Oman', 'OM', 'OMN', '512');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Pakistan', 'PK', 'PAK', '586');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Palau', 'PW', 'PLW', '585');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Palestine, State of', 'PS', 'PSE', '275');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Panama', 'PA', 'PAN', '591');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Papua New Guinea', 'PG', 'PNG', '598');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Paraguay', 'PY', 'PRY', '600');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Peru', 'PE', 'PER', '604');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Philippines', 'PH', 'PHL', '608');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Pitcairn', 'PN', 'PCN', '612');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Poland', 'PL', 'POL', '616');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Portugal', 'PT', 'PRT', '620');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Puerto Rico', 'PR', 'PRI', '630');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Qatar', 'QA', 'QAT', '634');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Réunion', 'RE', 'REU', '638');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Romania', 'RO', 'ROU', '642');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Russian Federation', 'RU', 'RUS', '643');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Rwanda', 'RW', 'RWA', '646');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Samoa', 'WS', 'WSM', '882');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('San Marino', 'SM', 'SMR', '674');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Sao Tome and Principe', 'ST', 'STP', '678');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Saudi Arabia', 'SA', 'SAU', '682');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Senegal', 'SN', 'SEN', '686');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Serbia, Republic of', 'RS', 'SRB', '688');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Seychelles', 'SC', 'SYC', '690');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Sierra Leone', 'SL', 'SLE', '694');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Singapore', 'SG', 'SGP', '702');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Sint Maarten', 'SX', 'SXM', '534');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Slovakia', 'SK', 'SVK', '703');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Slovenia', 'SI', 'SVN', '705');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Solomon Islands', 'SB', 'SLB', '90');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Somalia', 'SO', 'SOM', '706');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('South Africa', 'ZA', 'ZAF', '710');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('South Sudan', 'SS', 'SSD', '728');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Spain', 'ES', 'ESP', '724');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Sri Lanka', 'LK', 'LKA', '144');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('St. Helena', 'SH', 'SHN', '654');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('St. Kitts and Nevis', 'KN', 'KNA', '659');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('St. Lucia', 'LC', 'LCA', '662');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('St. Martin', 'MF', 'MAF', '663');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('St. Pierre and Miquelon', 'PM', 'SPM', '666');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('St. Vincent and the Grenadines', 'VC', 'VCT', '670');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Sudan', 'SD', 'SDN', '736');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Suriname', 'SR', 'SUR', '740');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Svalbard and Jan Mayen Islands', 'SJ', 'SJM', '744');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Swaziland', 'SZ', 'SWZ', '748');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Sweden', 'SE', 'SWE', '752');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Switzerland', 'CH', 'CHE', '756');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Syrian Arab Republic', 'SY', 'SYR', '760');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Taiwan', 'TW', 'TWN', '158');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Tajikistan', 'TJ', 'TJK', '762');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Tanzania, United Republic of', 'TZ', 'TZA', '834');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Thailand', 'TH', 'THA', '764');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Timor-Leste', 'TL', 'TLS', '626');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Togo', 'TG', 'TGO', '768');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Tokelau', 'TK', 'TKL', '772');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Tonga', 'TO', 'TON', '776');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Trinidad and Tobago', 'TT', 'TTO', '780');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Tunisia', 'TN', 'TUN', '788');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Turkey', 'TR', 'TUR', '792');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Turkmenistan', 'TM', 'TKM', '795');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Turks and Caicos Islands', 'TC', 'TCA', '796');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Tuvalu', 'TV', 'TUV', '798');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Uganda', 'UG', 'UGA', '800');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Ukraine', 'UA', 'UKR', '804');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('United Arab Emirates', 'AE', 'ARE', '784');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('United Kingdom', 'GB', 'GBR', '826');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('United Nations Interim Administration Mission in Kosovo', 'QZ', 'QZZ', '900');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('United States', 'US', 'USA', '840');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('United States Minor Outlying Islands', 'UM', 'UMI', '581');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('United States Virgin Islands', 'VI', 'VIR', '850');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Uruguay', 'UY', 'URY', '858');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Uzbekistan', 'UZ', 'UZB', '860');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Vanuatu', 'VU', 'VUT', '548');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Venezuela', 'VE', 'VEN', '862');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Vietnam', 'VN', 'VNM', '704');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Wallis and Futuna Islands', 'WF', 'WLF', '876');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Western Sahara', 'EH', 'ESH', '732');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Yemen', 'YE', 'YEM', '887');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Zambia', 'ZM', 'ZMB', '894');
INSERT INTO `country` (`countryName`, `countryCode2Char`, `countryCodeAlpha`, `countryCode`) VALUES ('Zimbabwe', 'ZW', 'ZWE', '716');
