INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Afghanistan', 'AFGHANI', 'AFN', '971');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Afghanistan', 'AFGHANI', 'AFA', '4');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Albania', 'LEK', 'ALL', '8');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Algeria', 'ALGERIAN DINAR', 'DZD', '12');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('American Samoa', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Andorra', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Angola', 'KWANZA', 'AOA', '973');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Anguilla', 'E. CARIBBEAN DOLLAR', 'XCD', '951');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Antarctica', 'NORWEGIAN KRONE', 'NOK', '578');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Antigua and Barbuda', 'E. CARIBBEAN DOLLAR', 'XCD', '951');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Argentina', 'ARGENTINE PESO', 'ARS', '32');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Armenia', 'ARMENIAN DRAM', 'AMD', '51');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Aruba', 'ARUBAN GUILDER', 'AWG', '533');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Australia', 'AUSTRALIAN DOLLAR', 'AUD', '36');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Austria', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Azerbaijan', 'AZERBAIJANIAN MANAT', 'AZM', '31');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Azerbaijan', 'AZERBAIJAN MANAT', 'AZN', '944');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bahamas', 'BAHAMIAN DOLLAR', 'BSD', '44');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bahrain', 'BAHRAINI DINAR', 'BHD', '48');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bangladesh', 'TAKA', 'BDT', '50');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Barbados', 'BARBADOS DOLLAR', 'BBD', '52');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Belarus', 'BELARUSSIAN RUBLE', 'BYR', '974');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Belarus', 'BELARUSSIAN RUBLE', 'BYN', '933');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Belgium', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Belize', 'BELIZE DOLLAR', 'BZD', '84');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Benin', 'CFA FRANC BCEAO', 'XOF', '952');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bermuda', 'BERMUDIAN DOLLAR', 'BMD', '60');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bhutan', 'BHUTAN NGULTRUM', 'BTN', '64');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bhutan', 'INDIAN RUPEE', 'INR', '356');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bolivia', 'BOLIVIANO', 'BOB', '68');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bosnia and Herzegovina', 'CONVERTIBLE MARK', 'BAM', '977');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Botswana', 'PULA', 'BWP', '72');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bouvet Island', 'NORWEGIAN KRONE', 'NOK', '578');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Brazil', 'BRAZILIAN CRUZEIRO', 'BRE', '76');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Brazil', 'BRAZILIAN REAL', 'BRL', '986');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('British Indian Ocean Territory', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('British Virgin Islands', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Brunei Darussalam', 'BRUNEI DOLLAR', 'BND', '96');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Bulgaria', 'BULGARIAN LEV', 'BGN', '975');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Burkina Faso', 'CFA FRANC BCEAO', 'XOF', '952');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Burundi', 'BURUNDI FRANC', 'BIF', '108');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cambodia', 'RIEL', 'KHR', '116');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cameroon, United Republic of', 'CFA FRANC BEAC', 'XAF', '950');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Canada', 'CANADIAN DOLLAR', 'CAD', '124');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cape Verde Island', 'CAPE VERDE ESCUDO', 'CVE', '132');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cayman Islands', 'CAYMAN IS. DOLLAR', 'KYD', '136');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Central African Republic', 'CFA FRANC BEAC', 'XAF', '950');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Chad', 'CFA FRANC BEAC', 'XAF', '950');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Chile', 'CHILEAN PESO', 'CLP', '152');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('China', 'YUAN RENMINBI', 'CNY', '156');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Christmas Island', 'AUSTRALIAN DOLLAR', 'AUD', '36');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cocos (Keeling) Islands', 'AUSTRALIAN DOLLAR', 'AUD', '36');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Colombia', 'COLOMBIAN PESO', 'COP', '170');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Comoros', 'COMORO FRANC', 'KMF', '174');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Congo', 'CFA FRANC BEAC', 'XAF', '950');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cook Islands', 'NEW ZEALAND DOLLAR', 'NZD', '554');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Costa Rica', 'COSTA RICAN COLON', 'CRC', '188');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Côte d\'Ivoire (Ivory Coast)', 'CFA FRANC BCEAO', 'XOF', '952');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Croatia', 'CROATIAN KUNA', 'HRK', '191');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cuba', 'CUBAN PESO', 'CUP', '192');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cyprus', 'CYPRUS POUND', 'CYP', '196');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Cyprus', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Czech Republic', 'CZECH KORUNA', 'CZK', '203');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Democratic Republic of the Congo', 'FRANC CONGOLAIS', 'CDF', '976');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Denmark', 'DANISH KRONE', 'DKK', '208');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Djibouti', 'DJIBOUTI FRANC', 'DJF', '262');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Dominica', 'E. CARIBBEAN DOLLAR', 'XCD', '951');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Dominican Republic', 'DOMINICAN PESO', 'DOP', '214');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Ecuador', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Egypt', 'EGYPTIAN POUND', 'EGP', '818');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('EL Salvador', 'EL SALVADOR COLON', 'SVC', '222');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('El Salvador', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Equatorial Guinea', 'CFA FRANC BEAC', 'XAF', '950');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Eritrea', 'ERITREAN NAKFA', 'ERN', '232');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Estonia', 'ESTONIAN KROON', 'EEK', '233');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Estonia', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Ethiopia', 'ETHIOPIAN BIRR', 'ETB', '230');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Falkland Islands (Malvinas)', 'FALKLAND IS. POUND', 'FKP', '238');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Faroe Islands', 'DANISH KRONE', 'DKK', '208');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Fiji', 'FIJI DOLLAR', 'FJD', '242');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Finland', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('France', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('French Guiana', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('French Polynesia', 'CFP FRANC', 'XPF', '953');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('French Southern Territories', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Gabon', 'CFA FRANC BEAC', 'XAF', '950');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Gambia', 'DALASI', 'GMD', '270');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Georgia', 'LARI', 'GEL', '981');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Germany', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Ghana', 'CEDI', 'GHS', '936');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Ghana', 'GHANA CEDI', 'GHC', '288');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Gibralter', 'GIBRALTAR POUND', 'GIP', '292');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Greece', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Greenland', 'DANISH KRONE', 'DKK', '208');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Grenada', 'E. CARIBBEAN DOLLAR', 'XCD', '951');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Guadeloupe', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Guam', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Guatemala', 'QUETZAL', 'GTQ', '320');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Guinea', 'GUINEA FRANC', 'GNF', '324');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Guinea-Bissau', 'GUINEA-BISSAU PESO', 'GWP', '624');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Guinea-Bissau', 'CFA FRANC BCEAO', 'XOF', '952');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Guyana', 'GUYANA DOLLAR', 'GYD', '328');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Haiti', 'GOURDE', 'HTG', '332');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Heard and McDonald Islands', 'GOURDE', 'HTG', '332');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Holy See (Vatican City State)', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Honduras', 'LEMPIRA', 'HNL', '340');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Hong Kong', 'HONG KONG DOLLAR', 'HKD', '344');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Hungary', 'FORINT', 'HUF', '348');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Iceland', 'ICELAND KRONA', 'ISK', '352');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('India', 'INDIAN RUPEE', 'INR', '356');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Indonesia', 'RUPIAH', 'IDR', '360');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Iran, Islamic Republic of', 'IRANIAN RIAL', 'IRR', '364');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Iran, Islamic Republic of', 'IRANIAN AIRLINE RATE', 'IRA', '365');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Iraq', 'IRAQI DINAR', 'IQD', '368');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Ireland, Republic of', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Israel', 'NEW ISRAELI SHEKEL', 'ILS', '376');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Italy', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Jamaica', 'JAMAICAN DOLLAR', 'JMD', '388');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Japan', 'YEN', 'JPY', '392');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Jordan', 'JORDANIAN DINAR', 'JOD', '400');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Kazakhstan', 'TENGE', 'KZT', '398');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Kenya', 'KENYAN SHILLING', 'KES', '404');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Kiribati', 'AUSTRALIAN DOLLAR', 'AUD', '36');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Kuwait', 'KUWAITI DINAR', 'KWD', '414');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Kyrgyzstan', 'SOM', 'KGS', '417');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Laos', 'KIP', 'LAK', '418');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Latvia', 'LATVIAN LATS', 'LVL', '428');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Latvia', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Lebanon', 'LEBANESE POUND', 'LBP', '422');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Lesotho', 'LESOTHO LOTI', 'LSL', '426');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Liberia', 'LIBERIAN DOLLAR', 'LRD', '430');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Libyan Arab Jamahiriya', 'LIBYAN DINAR', 'LYD', '434');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Liechtenstein', 'SWISS FRANC', 'CHF', '756');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Lithuania', 'LITHUANIAN LITAS', 'LTL', '440');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Luxembourg', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Macau, China', 'PATACA', 'MOP', '446');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Macedonia', 'DENAR', 'MKD', '807');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Madagascar', 'MALAGASY ARIARY', 'MGA', '969');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Malawi', 'MALAWI KWACHA', 'MWK', '454');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Malaysia', 'MALAYSIAN RINGGIT', 'MYR', '458');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Maldives', 'RUFIYAA', 'MVR', '462');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Mali', 'CFA FRANC BCEAO', 'XOF', '952');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Malta', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Marshall Islands', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Martinique', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Mauritania', 'OUGUIYA', 'MRO', '478');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Mauritius', 'MAURITIUS RUPEE', 'MUR', '480');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Mayotte', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Mexico', 'MEXICAN PESO', 'MXN', '484');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Micronesia', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Moldova, Republic of', 'MOLDOVAN LEU', 'MDL', '498');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Monaco', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Mongolia', 'TUGRIK', 'MNT', '496');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Montenegro', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Morocco', 'MOROCCAN DIRHAM', 'MAD', '504');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Mozambique', 'MOZAMBIQUE METICAL', 'MZN', '943');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Myanmar', 'KYAT', 'MMK', '104');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Namibia', 'NAMIBIA DOLLAR', 'NAD', '516');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Nauru', 'AUSTRALIAN DOLLAR', 'AUD', '36');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Nepal', 'NEPALESE RUPEE', 'NPR', '524');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Netherlands', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Netherlands', 'NETH. ANTI. GUILDER', 'ANG', '532');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('New Caledonia', 'CFP FRANC', 'XPF', '953');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('New Zealand', 'NEW ZEALAND DOLLAR', 'NZD', '554');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Nicaragua', 'CORDOBA ORO', 'NIO', '558');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Niger', 'CFA FRANC BCEAO', 'XOF', '952');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Nigeria', 'NAIRA', 'NGN', '566');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Niue', 'NEW ZEALAND DOLLAR', 'NZD', '554');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Norfolk Island', 'AUSTRALIAN DOLLAR', 'AUD', '36');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Northern Mariana Islands', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Norway', 'NORWEGIAN KRONE', 'NOK', '578');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Oman', 'RIAL OMANI', 'OMR', '512');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Pakistan', 'PAKISTAN RUPEE', 'PKR', '586');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Palau', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Palestine, State of', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Panama', 'BALBOA', 'PAB', '590');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Papua New Guinea', 'KINA', 'PGK', '598');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Paraguay', 'GUARANI', 'PYG', '600');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Peru', 'NUEVO SOL', 'PEN', '604');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Philippines', 'PHILIPPINE PESO', 'PHP', '608');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Pitcairn', 'NEW ZEALAND DOLLAR', 'NZD', '554');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Poland', 'ZLOTY', 'PLN', '985');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Portugal', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Puerto Rico', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Qatar', 'QATARI RIAL', 'QAR', '634');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Réunion', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Romania', 'LEU', 'RON', '946');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Romania', 'ROMANIAN LEU', 'ROL', '642');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Russian Federation', 'RUSSIAN RUBLE', 'RUR', '810');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Russian Federation', 'RUSSIAN RUBLE', 'RUB', '643');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Rwanda', 'RWANDA FRANC', 'RWF', '646');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Samoa', 'TALA', 'WST', '882');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('San Marino', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Sao Tome and Principe', 'DOBRA', 'STD', '678');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Saudi Arabia', 'SAUDI RIYAL', 'SAR', '682');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Senegal', 'CFA FRANC BCEAO', 'XOF', '952');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Serbia, Republic of', 'SERBIAN DINAR', 'RSD', '941');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Serbia, Republic of', 'SERBIAN DINAR', 'CSD', '891');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Seychelles', 'SEYCHELLES RUPEE', 'SCR', '690');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Sierra Leone', 'LEONE', 'SLL', '694');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Singapore', 'SINGAPORE DOLLAR', 'SGD', '702');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Slovakia', 'SLOVAK KORUNA', 'SKK', '703');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Slovakia', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Slovenia', 'SLOVENIAN TOLAR', 'SIT', '705');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Slovenia', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Solomon Islands', 'SOLOMON IS. DOLLAR', 'SBD', '90');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Somalia', 'SOMALI SHILLING', 'SOS', '706');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('South Africa', 'RAND', 'ZAR', '710');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('South Georgia and the South Sandwich Islands', 'POUND STERLING', 'GBP', '826');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Spain', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Sri Lanka', 'SRI LANKA RUPEE', 'LKR', '144');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('St. Helena', 'ST. HELENA POUND', 'SHP', '654');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('St. Kitts and Nevis', 'E. CARIBBEAN DOLLAR', 'XCD', '951');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('St. Lucia', 'E. CARIBBEAN DOLLAR', 'XCD', '951');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('St. Pierre and Miquelon', 'EURO', 'EUR', '978');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('St. Vincent and the Grenadines', 'E. CARIBBEAN DOLLAR', 'XCD', '951');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Sudan', 'SUDANESE POUND', 'SDG', '938');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Sudan', 'SUDANESE DINAR', 'SDD', '736');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Sudan', 'SUDAN AIRLINE RATE', 'SDA', '737');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Sudan', 'SOUTH SUDANESE POUND', 'SSP', '728');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Suriname', 'SURINAM GUILDER', 'SRG', '740');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Suriname', 'SURINAME DOLLAR', 'SRD', '968');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Svalbard and Jan Mayen Islands', 'NORWEGIAN KRONE', 'NOK', '578');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Swaziland', 'LILANGENI', 'SZL', '748');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Sweden', 'SWEDISH KRONA', 'SEK', '752');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Switzerland', 'SWISS FRANC', 'CHF', '756');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Syrian Arab Republic', 'SYRIAN POUND', 'SYP', '760');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Taiwan', 'NEW TAIWAN DOLLAR', 'TWD', '901');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Tajikistan', 'SOMONI', 'TJS', '972');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Tanzania, United Republic of', 'TANZANIAN SHILLING', 'TZS', '834');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Thailand', 'BAHT', 'THB', '764');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Timor-Leste', 'TIMOR ESCUDO', 'TPE', '626');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Timor-Leste', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Togo', 'CFA FRANC BCEAO', 'XOF', '952');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Tokelau', 'NEW ZEALAND DOLLAR', 'NZD', '554');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Tonga', 'PA\'ANGA', 'TOP', '776');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Trinidad and Tobago', 'TRINI & TOBA DOLLAR', 'TTD', '780');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Tunisia', 'TUNISIAN DINAR', 'TND', '788');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Turkey', 'TURKISH LIRA', 'TRL', '792');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Turkey', 'TURKISH LIRA', 'TRY', '949');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Turkmenistan', 'TURKMENISTAN MANAT', 'TMM', '795');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Turkmenistan', 'TURKMENISTAN MANAT (New)', 'TMT', '934');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Turks and Caicos Islands', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Tuvalu', 'AUSTRALIAN DOLLAR', 'AUD', '36');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Uganda', 'UGANDA SHILLING', 'UGX', '800');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Ukraine', 'UKRAINIAN HRYVNIA', 'UAH', '980');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('United Arab Emirates', 'U.A.E. DIRHAM', 'AED', '784');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('United Kingdom', 'POUND STERLING', 'GBP', '826');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('United States', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('United States Minor Outlying Islands', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('United States Virgin Islands', 'U.S. DOLLAR', 'USD', '840');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Uruguay', 'PESO URUGUAYO', 'UYU', '858');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Uzbekistan', 'UZBEKISTAN SUM', 'UZS', '860');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Vanuatu', 'VATU', 'VUV', '548');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Venezuela', 'Bolivar Soberano (Sovereign Bolivar)', 'VES', '928');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Vietnam', 'DONG', 'VND', '704');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Wallis and Futuna Islands', 'CFP FRANC', 'XPF', '953');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Western Sahara', 'MOROCCAN DIRHAM', 'MAD', '504');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Yemen', 'YEMENI RIAL', 'YER', '886');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Zambia', 'ZAMBIAN KWACHA', 'ZMW', '967');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Zambia', 'ZAMBIAN KWACHA', 'ZMK', '894');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Zimbabwe', 'Zimbabwe', 'ZWL', '932');
INSERT INTO `currency` (`countryName`, `currencyName`, `currencyCodeAlpha`, `currencyCode`) VALUES ('Zimbabwe', 'ZIMBABWE DOLLAR', 'ZWD', '716');
